### PR TITLE
Null Safety and Merge AppCenter

### PR DESCRIPTION
**Pull request by chandrabezzo**
## Description of the change
- Migrate to null safety
- Add AppCenter
- Follow effective dart
- Add pedantic
- Restructure Project
- Change Logger to Developer Log

> Description here
I create breaking changes migrate from non-null safety to null safety support. Add/Merge AppCenter from different [package](https://pub.dev/packages/rudder_integration_appcenter_flutter) to this package. Follow [Effective Dart](https://dart.dev/guides/language/effective-dart) for code implementation. I changed Logger to Developer Log, because Developer Log can logging very long message than Logger.
## Type of change
- [x] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Screenshoot
- [x] Run at Android
Screen Shot 2021-06-16 at 13 12 27
- [x] Run at iOS
Screen Shot 2021-06-16 at 13 14 16
- [x] RudderStack Logging iOS
Screen Shot 2021-06-16 at 13 10 06
- [x] RudderStack Logging Android
Screen Shot 2021-06-16 at 13 13 00

### Development
- [x] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 
- [x]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [x] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [x] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by arnab-p** [comment]
@chandrabezzo Can you please rebase with master and resolve the conflicts?

Also, we need you to sign the [CLA](https://rudderlabs.wufoo.com/forms/rudderlabs-contributor-license-agreement) before we can merge the PR.

**Comment by chandrabezzo** [comment]
> @chandrabezzo Can you please rebase with master and resolve the conflicts?
> 
> Also, we need you to sign the [CLA](https://rudderlabs.wufoo.com/forms/rudderlabs-contributor-license-agreement) before we can merge the PR.

Hi, I make breaking changes the file. So can your master follow my code? Because I make a changes to follow effective-dart.

**Comment by chandrabezzo** [comment]
> @chandrabezzo Can you please rebase with master and resolve the conflicts?
> 
> Also, we need you to sign the [CLA](https://rudderlabs.wufoo.com/forms/rudderlabs-contributor-license-agreement) before we can merge the PR.

@arnab-p @desusai7 I have renamed all file to follow [effective dart](https://dart.dev/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores)

**Comment by chandrabezzo** [comment]
> @chandrabezzo Can you please rebase with master and resolve the conflicts?
> 
> Also, we need you to sign the [CLA](https://rudderlabs.wufoo.com/forms/rudderlabs-contributor-license-agreement) before we can merge the PR.

Hi, I was signed the CLA.

**Comment by desusai7** [comment]
Hey @chandrabezzo, Thank you for Raising the PR on Null Safety.  Actually, we just released `rudder_sdk_flutter: ^1.0.2` with Null Safety. We greatly appreciate the efforts you had put in.

**Comment by chandrabezzo** [comment]
> Hey @chandrabezzo, Thank you for Raising the PR on Null Safety. Actually, we just released `rudder_sdk_flutter: ^1.0.2` with Null Safety. We greatly appreciate the efforts you had put in.

Ah ok, have you check my changes? My PR not just only focused migrate to null safety, merged with app center and follow effective dart as suggested from Google. Thank you.

**Comment by desusai7** [comment]
> > Hey @chandrabezzo, Thank you for Raising the PR on Null Safety. Actually, we just released `rudder_sdk_flutter: ^1.0.2` with Null Safety. We greatly appreciate the efforts you had put in.
> 
> Ah ok, have you check my changes? My PR not just only focused migrate to null safety, merged with app center and follow effective dart as suggested from Google. Thank you.

Yeah, saw those changes. We had decided on moving device modes to separate repositories. So Appcenter changes here were not accepted and effective dart suggestion we try to follow them in next releases

**Pull request closed without merging**
